### ISSUE TITLE
make create-sandbox fails

### ISSUE THREAD

**Issue by cokongwu** [GaloisInc/smaccmpilot-build#5]
I followed the build instructions at https://github.com/GaloisInc/smaccmpilot-build/blob/red-team-may-2015/red-team-may-2015.md, and got cabal errors that caused the build to fail.

[ 8 of 61] Compiling Ivory.Language.Syntax.Concrete.Lexer ( dist/dist-sandbox-af1b885b/build/Ivory/Language/Syntax/Concrete/Lexer.hs, dist/dist-sandbox-af1b885b/build/Ivory/Language/Syntax/Concrete/Lexer.o )

src/Ivory/Language/Syntax/Concrete/Lexer.x:255:38:
    Not in scope: ‘ord’
    Perhaps you meant one of these:
      ‘ord#’ (imported from GHC.Exts), ‘or#’ (imported from GHC.Exts),
      ‘or’ (imported from Prelude)
Failed to install ivory-0.1.0.2

**Comment by leepike** [comment]
That page is outdated. Now, the build is Stack-based. Perhaps the easiest way is to emulate the Travis-CI build (https://travis-ci.org/GaloisInc/ivory-tower-stm32/builds/117854002) by following the `travis.yml` and Makefile.
